version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - "DB_HOST=postgres"
  postgres:
    image: "postgres:9.5"
    volumes:
      - "./postgres:/docker-entrypoint-initdb.d"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "PGPASSWORD=postgres"
